NewsPaper_/NewsPaper_/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path('news/', include(('newsapp.urls', 'category'), namespace='category')),
   path('', include('protect.urls')),
   path('sign/', include('sign.urls')),
   path('accounts/', include('allauth.urls')),
]

NewsPaper_/newsapp/urls.py
from django.urls import path
from .views import (PostList, PostDetail, NewsCreate, NewsEdit, NewsDelete,
                    ArticleCreate, ArticleEdit, ArticleDelete, UserUpdateView, CategoryList,
                    add_subscribe,IndexView)


urlpatterns = [
   path('', PostList.as_view(), name='news'),
   path('<int:pk>', PostDetail.as_view(), name='post_detail'),
   path('create/', NewsCreate.as_view(), name='news_create'),
   path('<int:pk>/edit/', NewsEdit.as_view(), name='news_edit'),
   path('<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('article/create/', ArticleCreate.as_view(), name='article_create'),
    path('article/<int:pk>/edit/', ArticleEdit.as_view(), name='article_edit'),
    path('article/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    path('user/', UserUpdateView.as_view(), name='user_update'),
    path('category/', CategoryList.as_view(), name='category'),
    path('subscribe/<int:pk>', add_subscribe, name='subscribe'),
    path('app/',IndexView.as_view())
]

NewsPaper_/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView, upgrade_me

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),
    path('upgrade/', upgrade_me, name = 'upgrade')
]

NewsPaper_/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>New Article</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper_/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Delete the article</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure to delete "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper_/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Article editor</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />

</form>
{% endblock content %}

NewsPaper_/templates/category.html
{% extends 'flatpages/default.html' %}

{% block title %} Category list {% endblock title %}

{% block content %}
<p>&nbsp;</p>
Click to <span style="text-decoration: underline;">subscribe</span> to stay up to date <strong>{{user.username}}</strong>!
<p>&nbsp;</p>

<table style="height: 125px; " width="176">
    <thead>
        <th>
            Categories
        </th>
    </thead>
    {% for cat in category %}
    <tr>
       <td>
            {{ cat.name }}
           <a href="{% url 'category:subscribe' cat.id %}"><u>Subscribe!</u></a>


        </td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

NewsPaper_/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

NewsPaper_/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}News list{% endblock title %}
{% block content %}
<h1>News list</h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
      <input type="submit" value="Search" />
   </form>


   <h3>{{ time_now|date:'DD MM YYYY' }}</h3>
<p>&nbsp;</p>
<hr>
   {% if news %}
       <table>
           <tr>
               <td style="width: 200.55px; text-align: center;"><h3>Header</h3></td>
                <td style="width: 200.55px; text-align: center;"><h3>Type</h3></td>
               <td style="width: 200.55px; text-align: center;"><h3>Post</h3></td>
               <td style="width: 200.55px; text-align: center;"><h3>Publication date</h3></td>
               <td style="width: 200.55px; text-align: center;"><h3>Category type</h3></td>

           </tr>

           {% for n in news %}
           <tr>

               <td style="width: 200.55px; text-align: center;">{{ n.title|censor|truncatechars:20 }}</td>
               <td style="width: 200.55px; text-align: center;">{{ n.categoryType }}</td>
               <td style="width: 200.55px; text-align: center;">{{ n.text|censor|truncatechars:20 }}</td>
               <td style="width: 200.55px; text-align: center;">{{ n.dateCreation }}</td>
               <td style="width: 200.55px; text-align: center;" >{% for i in n.postCategory.all %}{{ i }}{% endfor %}</td>


           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>The newsfeed is empty for today!</h2>
   {% endif %}
<p>&nbsp;</p>
   {% if page_obj.has_previous %}

       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper_/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>New Post</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper_/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Delete the news</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure to delete "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper_/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>News editor</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper_/templates/newsid.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}Intresting Post{% endblock title %}
{% block content %}
{{post.dateCreation}}
<h2>{{post.title|censor}}</h2>
<h3>{{post.text|censor}}</h3>
{% endblock content %}

NewsPaper_/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block content %}
<h1>Let's find the post...</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper_/templates/sender.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Weekly news: {{ category_name  }} </title>
</head>
<body>
    <h1> Greetings, {{ user }}, new paper in your favorite category {{ category_name  }} for the las week ({{ week_number_last }}) ! </h1>
<hr>
{% for news in text %}
{{ news }}
{% endfor%}
<br>
</body>
</html>

NewsPaper_/templates/user_update.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Registration page</h1>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change" />
</form>
{% endblock content %}